Blog.Web/Controllers/AboutUsController.cs
using System.Linq;
using Blog.Data.Context;
using Blog.Data.Enums;
using Blog.Data.Models;
using Microsoft.AspNetCore.Mvc;



namespace Blog.Web.Controllers
{
    public class AboutUsController : Controller
    {

        private readonly BlogContext _blogContext;
            public AboutUsController(BlogContext blogContext)
        {
            _blogContext = blogContext;
        }

            
        public IActionResult Index()
        {
                Page page = _blogContext.Pages.FirstOrDefault(a => !a.Deleted && a.PageKind == PageKind.About);

            return View(page);
        }
    }
}

Blog.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Data.Context;
using Blog.Data.Dto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly BlogContext _blogContext;

            public BlogController(BlogContext blogContext)
        {
            _blogContext = blogContext;
        }

        public IActionResult New()
        {
            List<Data.Models.Category> categories = _blogContext.Categories.Where(a => !a.Deleted).ToList();

            return View(categories);
        }

        public IActionResult Add([FromBody] BlogAddDto blogAdd)
        {
            int UserId = HttpContext.Session.GetInt32("UserId").Value;
            Blog.Data.Models.Blog blog = new Blog.Data.Models.Blog()
            {
                UserId= UserId,
                Title=blogAdd.Title,
                Content=blogAdd.Content,
                CreateDate=DateTime.UtcNow,
                Hit=0,
                Deleted =false,
                CategoryId=0
            };


            _blogContext.Blogs.Add(blog);
            _blogContext.SaveChanges();

            return Ok();
        }
    }

}

Blog.Web/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Data.Context;
using Blog.Data.Dto;
using Blog.Data.Migrations;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class ContactController : Controller
    {
        private readonly BlogContext _blogContext;
        public ContactController(BlogContext blogContext)
        {
            _blogContext = blogContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Send([FromBody]ContactSendDto contactSend)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            _blogContext.Contacts.Add(new Data.Models.Contact()
            {
                Name = contactSend.Name,
                Surname= contactSend.Surname,
                Message =contactSend.Message,
                CreateDate=DateTime.UtcNow
            });

            _blogContext.SaveChanges();

            return new JsonResult("ok");
        }
    }
}

Blog.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Blog.Web/Controllers/UserController.cs
using Blog.Data.Context;
using Blog.Data.Dto;
using Blog.Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Blog.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly BlogContext _blogContext;
        public UserController(BlogContext blogContext)
        {
            _blogContext = blogContext;
        }

        

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public IActionResult LoginAction ([FromBody] UserLoginDto userLogin)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Invalid validation");
            }
            User user = _blogContext.Users.SingleOrDefault(a =>
            !a.Deleted && a.Email == userLogin.Email && a.Password == userLogin.Password);
            if (user != null)
            {
                HttpContext.Session.SetInt32("UserId", user.Id);
                return Ok(user);
            }
            else
            {
                return Unauthorized();
            }
               
        }

        [HttpGet]
        public IActionResult LogoutAction()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog.Web/Views/AboutUs/Index.cshtml
@model Blog.Data.Models.Page
@{
    Layout = "_Layout";
}


@Model.Name
<br />
@Model.Content

Blog.Web/Views/Blog/New.cshtml
@model List<Blog.Data.Models.Category>
@{
    Layout = "_Layout";
}
<div>
    <select>
        <option disabled="disabled">Bir Seçim Yap Dostum!</option>
        <option>Bu Bir Seçim</option>
        @{ 
            foreach(var category in Model)
            {
                <option value="@category.Id">@category.Name</option>
            }
        }
    </select>
</div>


<div>
<input type="text" id="Title" placeholder="Yazı başlığı"  />
</div>
<div>
<textarea id="Content" placeholder="İçerik..."></textarea>  
</div>
<div>
<input type="button" value="kaydet" onclick="Page.Blog.New.Save();"/>
</div>

Blog.Web/Views/Contact/Index.cshtml
@{
    Layout = "_Layout";
}
<div id="Contact-Index-Form">
    <form>
        <input type="text" id="Name" placeholder="Adınız" />
        <br />
        <input type="text" id="Surname" placeholder="Soyadınız" />
        <br />
        <textarea id="Message" placeholder="Mesajınız..."></textarea>
        <br />
        <input type="button" value="Gönder" onclick="Page.Contact.Send();" />

    </form>
</div>
<div id="Contact-Index-Sending" style="display:none;">
    <h3>İletiniz Gönderiliyor...</h3>
</div>
<div id="Contact-Index-Sent"style="display:none;">
    <h3>İletiniz gönderildi...</h3>
</div>

Blog.Web/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}



content burada yer ar

Blog.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <title> Bu Sitenin Başlığı!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="~/js/Page.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <div><a href="@Url.Action("Index","Home")">Anasayfa</a></div>
                <div><a href="@Url.Action("Index","AboutUs")">Hakkımda</a></div>
                <div><a href="@Url.Action("Index","Contact")">İletişim</a></div>
                @{
                    int? userId = Context.Session.GetInt32("UserId");
                    if (userId != null && userId != 0)
                    {
                        <div><a href="@Url.Action("New","Blog")">Yeni</a></div>
                        <div><a href="@Url.Action("LogoutAction","User")">Çıkış Yap</a></div>
                    }
                    else
                    {
                        <div><a href="@Url.Action("Login","User")">Kullanıcı Girişi</a></div>
                    }
                }

            </div>
            <div class="col-8">@RenderBody()</div>
        </div>
</body>

</html>

Blog.Web/Views/User/Login.cshtml
@{
    Layout = "_Layout";
}

<form>
    <div>
        <input type="text" placeholder="E-Posta"id="Email" />
    </div>
    <div>
        <input type="password" placeholder="Şifre" id="Password" />
    </div>
    <div>
        <input type="button" value="Giriş Yap" onclick="Page.User.Login.LoginButton();" />
    </div>
</form>